# Setup
name:         Longchi Catherine
description:  This blog is about my Outreachy internship with Ceph
url:          https://tetekate2.github.io/outreachy/2018/12/07/my-journey-to-outreachy.html
locale:       "en"

# Gems
plugins:
  - jekyll-paginate
#- jekyll-feed

#Others
markdown: kramdown
